[package]
authors = ["Madeline Sparkles <madeline@mouse.lgbt>", "Mae Rosaline <mae@maestoso.online>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4"

vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
vulkano = "0.33.0"
winit = "0.28.3"

egui_winit_vulkano = "0.24.0"
egui = "0.21.0"

webbrowser = "0.8.10"

string-interner = "0.14.0"
slice-group-by = "0.3.0"
hexagon-tiles = { git = "https://github.com/Mg138/hexagon-tiles" }
predicates = "3.0.2"
fuse-rust = "0.3.1"
genmesh = "0.6.2"
flexstr = { version = "0.9.2", features = ["serde", "fast_format"] }
uuid = { version = "1.2.2", features = ["v4"] }

lazy_static = "1.4.0"
hashbrown = { version = "0.14.0", features = ["serde", "rayon"] }
bytemuck = "1.8.0"
walkdir = "2.3.3"
cgmath = "0.18.0"
rayon = "1.7.0"
kira = "0.8.3"
rand = "0.8.5"
num = "0.4.0"
chrono = "0.4.24"

serde_json = "1.0.87"
serde = { version = "1.0", features = ["derive"] }

ply-rs = "0.1.3"
image = "0.24.6"
zstd = "0.12.3"

async-trait = "0.1.68"
futures = "0.3.28"
ractor = "0.8"
tokio = { version = "1", features = ["full"] }