[package]
authors = ["Madeline Sparkle <muguang138@gmail.com>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
env_logger = "0.9"
log = "0.4"
paste = "1.0.7"

vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
winit = "0.26"

egui = "0.18.1"

zstd = "*"
#async-compression = { version = "0.3.14", features = ["tokio", "zstd"] }
bytemuck = "1.8.0"
cgmath = "0.18"
rand = "0.8.5"

json = "0.12.4"
png = "0.17.5"
ply-rs = "0.1.3"

lazy_static = "*"
futures = "*"
tokio = { version = "1.18.2", features = ["full"] }