[package]
authors = ["Madeline Sparkle <muguang138@gmail.com>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4"

vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
vulkano = "0.32.3"

winit = "0.27.5"

egui = "0.20.1"

lazy_static = "1.4.0"
walkdir = "2.3.2"
paste = "1.0.7"

hexagon_tiles = { git = "https://github.com/Mg138/hexagon-tiles" }
bytemuck = "1.8.0"
flexstr = { version = "0.9.2", features = ["serde", "fast_format"] }
cgmath = "0.18.0"
rand = "0.8.5"
num = "0.4.0"

serde_json = "1.0.87"
serde = { version = "1.0", features = ["derive"] }

ply-rs = "0.1.3"
zstd = "*"
json = "0.12.4"
png = "0.17.5"

futures-executor = "0.3.25"
futures-task = "0.3.25"
futures-util = "0.3.25"
futures = "0.3.25"

riker-patterns = "0.4.2"
riker = "0.4.2"
