[package]
authors = ["Madeline Sparkles <madeline@mouse.lgbt>", "Mae Rosaline <mae@maestoso.online>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "automancy"

[dependencies]
automancy_resources = { path = "src/automancy_resources" }
automancy_defs = { path = "src/automancy_defs" }

env_logger = "0.10.0"

webbrowser = "0.8.10"

slice-group-by = "0.3.0"
predicates = "3.0.2"
fuse-rust = "0.3.1"
genmesh = "0.6.2"
uuid = { version = "1.2.2", features = ["v4"] }

lazy_static = "1.4.0"
rayon = "1.7.0"
rand = "0.8.5"
num = "0.4.0"

image = "0.24.6"
zstd = "0.12.3"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.4"

vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
vulkano = "0.33.0"

async-trait = "0.1.68"
futures = "0.3.28"
ractor = "0.8"
tokio = { version = "1", features = ["full"] }