[package]
authors = ["Madeline Sparkles <sparkles.system@gmail.com>", "Mae Rosaline <mae@maestoso.online>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4"

vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
vulkano = "0.32.3"
winit = "0.27.5"

egui_winit_vulkano = { git = "https://github.com/Mg138/egui_winit_vulkano" }
egui = "0.20.1"

discord-rich-presence = "0.2.3"
string-interner = "0.14.0"
hexagon_tiles = { git = "https://github.com/Mg138/hexagon-tiles" }
fuse-rust = "0.3.1"
bytemuck = "1.8.0"
flexstr = { version = "0.9.2", features = ["serde", "fast_format"] }
cgmath = "0.18.0"
uuid = { version = "1.2.2", features = ["v4"] }
rand = "0.8.5"
num = "0.4.0"

kira = "0.7.1"

serde_json = "1.0.87"
serde = { version = "1.0", features = ["derive"] }

ply-rs = "0.1.3"
zstd = "0.12.3"
json = "0.12.4"
png = "0.17.5"

futures-executor = "0.3.25"
futures-timer = "3.0.2"
futures-task = "0.3.25"
futures-util = "0.3.25"
futures = "0.3.25"

riker-patterns = "0.4.2"
riker = "0.4.2"

rune = "0.12.0"