[package]
authors = ["Madeline Sparkles <madeline@mouse.lgbt>", "Mae Rosaline <mae@maestoso.online>"]
name = "automancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[workspace]
members = [
    "automancy_defs",
    "automancy_macros",
    "automancy_resources"
]



[[bin]]
name = "automancy"



[workspace.dependencies]
automancy_defs = { path = "automancy_defs" }
automancy_macros = { path = "automancy_macros" }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

wgpu = { version = "0.16.1", features = ["spirv"] }

egui = { version = "0.22.0", default-features = false, features = ["log"] }
egui-wgpu = { version = "0.22.0" }
egui-winit = "0.22.0"

winit = "0.28.3"

lazy_static = "1.4.0"



[dependencies]
automancy_defs = { workspace = true }
automancy_macros = { workspace = true }

serde_json = { workspace = true }
serde = { workspace = true }

wgpu = { workspace = true }

egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }

winit = { workspace = true }

lazy_static = { workspace = true }



automancy_resources = { path = "automancy_resources" }

env_logger = "0.10.0"

slice-group-by = "0.3.0"
arraydeque = "0.5.1"
fuse-rust = "0.3.1"

rayon = "1.7.0"
rand = "0.8.5"
num = "0.4.0"

image = "0.24.6"
zstd = "0.12.3"

toml = "0.7.4"

async-trait = "0.1.68"
futures = "0.3.28"
ractor = "0.8"
tokio = { version = "1", features = ["full"] }
