[package]
name = "automancy_defs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }

wgpu = { workspace = true }

egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }

winit = { workspace = true }

rhai = { workspace = true }



log = "0.4"

string-interner = { git = "https://github.com/automancy/string-interner" }
hexagon-tiles = { git = "https://github.com/automancy/hexagon-tiles" }
hashbrown = { version = "0.14.0", features = ["serde", "rayon"] }
bytemuck = "1.8.0"
flexstr = { version = "0.9.2", features = ["serde", "fast_format"] }
cgmath = "0.18.0"
color-hex = "0.2.0"
slice-group-by = "0.3.0"

gltf = "1.2.0"