[package]
name = "automancy_defs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
vulkano-shaders = { workspace = true }
vulkano = { workspace = true }
winit = { workspace = true }

log = "0.4"

string-interner = { git = "https://github.com/sorcerers-class/string-interner" }
hexagon-tiles = { git = "https://github.com/Mg138/hexagon-tiles" }
hashbrown = { version = "0.14.0", features = ["serde", "rayon"] }
bytemuck = "1.8.0"
flexstr = { version = "0.9.2", features = ["serde", "fast_format"] }
ply-rs = "0.1.3"
cgmath = "0.18.0"

egui_winit_vulkano = { git = "https://github.com/sorcerers-class/egui_winit_vulkano" }
egui = "0.22.0"